# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r 
language: r

dist: xenial
sudo: false

matrix:
  include:
    - name: "Backend: TensorFlow | Implementation: Keras"
      env:
        - KERAS_BACKEND="tensorflow"
        - KERAS_IMPLEMENTATION="tensorflow"
        - TENSORFLOW_VERSION="default"
    - name: "Backend: Theano | Implementation: Keras"
      env:
        - KERAS_BACKEND="theano"
        - THEANO_FLAGS=optimizer=fast_compile
        - TENSORFLOW_VERSION="default"
    - name: "Backend: TensorFlow | Implementation: TensorFlow"
      env:
        - KERAS_BACKEND="tensorflow"
        - KERAS_IMPLEMENTATION="tensorflow"
        - TENSORFLOW_VERSION="default"
    - name: "Backend: TensorFlow Eager | Implementation: TensorFlow"
      env:
        - KERAS_BACKEND="tensorflow"
        - KERAS_IMPLEMENTATION="tensorflow"
        - TENSORFLOW_VERSION="default"
        - TENSORFLOW_EAGER="TRUE"
    - name: "Backend: TensorFlow | Implementation: TensorFlow 1.12"
      env:
        - KERAS_IMPLEMENTATION="tensorflow"
        - TENSORFLOW_VERSION="1.12.3"
    - name: "Backend: TensorFlow | Implementation: TensorFlow 1.13"
      env:
        - KERAS_IMPLEMENTATION="tensorflow"
        - TENSORFLOW_VERSION="1.13.2"
    - name: "Backend: TensorFlow | Implementation: TensorFlow 2.0.0"
      env:
        - KERAS_IMPLEMENTATION="tensorflow"
        - TENSORFLOW_VERSION="2.0.0"
    - name: "Backend: TensorFlow | Implementation: TensorFlow 1.14"
      env:
        - KERAS_IMPLEMENTATION="tensorflow"
        - TENSORFLOW_VERSION="1.14"
    - name: "Backend: Tensorflow | Implementation: TensorFlow Nightly"
      env:
        - TENSORFLOW_VERSION="nightly"
    - name: "Backend: Tensorflow Eager | Implementation: Tensorflow Nightly"
      env:
        - TENSORFLOW_VERSION="nightly"
        - TENSORFLOW_EAGER="TRUE"
    - name: "TensorFlow (release version) with reticulate master"
      env:
        - TENSORFLOW_VERSION="1.14"
      r_github_packages:
        - rstudio/reticulate
    - name: "TensorFlow (nightly) with reticulate master"
      env:
        - TENSORFLOW_VERSION="nightly"
      r_github_packages:
        - rstudio/reticulate
  allow_failures:
    - name: "Backend: Tensorflow | Implementation: TensorFlow Nightly"
      env:
        - TENSORFLOW_VERSION="nightly"
    - name: "Backend: Tensorflow Eager | Implementation: Tensorflow Nightly"
      env:
        - TENSORFLOW_VERSION="nightly"
        - TENSORFLOW_EAGER="TRUE"
    - name: "Backend: TensorFlow Eager | Implementation: TensorFlow"
      env:
        - KERAS_BACKEND="tensorflow"
        - KERAS_IMPLEMENTATION="tensorflow"
        - TENSORFLOW_VERSION="default"
        - TENSORFLOW_EAGER="TRUE"
    - name: "TensorFlow (nightly) with reticulate master"
      env:
        - TENSORFLOW_VERSION="nightly"
      r_github_packages:
        - rstudio/reticulate
        
cache:
  packages: true
  directories:
    - $HOME/.keras
    - $HOME/.cache/pip

before_script:
  - sudo apt-get update
  - sudo apt-get install python3 python3-pip
  - pip3 install --upgrade --ignore-installed --user travis virtualenv
  - R CMD INSTALL .
  - R -e 'keras::install_keras(tensorflow = Sys.getenv("TENSORFLOW_VERSION"), extra_packages = "IPython")'
  - R -e 'tensorflow::tf_config()'
  
after_failure:
  - Rscript -e 'library(keras); testthat::test_dir("tests/testthat/")'

notifications:
  email:
    recipients:
      - daniel@rstudio.com
      - sigrid@rstudio.com
    on_success: never
    on_failure: always
