# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

dist: trusty
sudo: false

env:
  - KERAS_IMPLEMENTATION="tensorflow"

cache:
  packages: true
  directories:
    - $HOME/.keras
    - $HOME/.cache/pip

before_script:
  - pip2.7 install --upgrade --ignore-installed --user travis pip setuptools wheel virtualenv
  - R -e 'tensorflow::install_tensorflow()'

